language: ruby
before_deploy:
  - rvm 2.4.0 do gem install mime-types -v 2.6.2
before_deploy:
  - gem install mime-types
dist: trusty
rvm:
  - 2.4.0
before_install: gem install bundler -v 1.16.1
sudo: required
dist: precise
